#---- Configuration files ----
conda_config: "workflow/envs/conda.yaml"

#---- Directory structure config ----
genome_dir: "genomes"
output_dir: "results"
log_dir: "logs"
cluster_log_dir: "cluster_logs"
busco_dir: "busco"
mafft_dir: "mafft"
gblocks_dir: "gblocks"
trimal_dir: "trimal"
iqtree_dir: "iqtree"
common_ids_dir: "common_ids"
single_copy_busco_sequences_dir: "single_copy_busco_sequences.common.dir"
merged_sequences_dir: "merged_sequences"
concat_aligments_dir: "concat_aligments"
benchmark_dir: "benchmarks"

#---- Tool threads ----
busco_threads: 4
mafft_threads: 4
gblocks_threads: 2
trimal_threads: 2
iqtree_threads: 10
common_ids_threads: 1

#---- Tool memory ----
busco_mem_mb: 20000
mafft_mem_mb: 20000
gblocks_mem_mb: 10000
trimal_mem_mb: 10000
iqtree_mem_mb: 10000
common_ids_mem_mb: 2000

#---- Tool time ----
busco_time: "60:00:00"
mafft_time: "60:00:00"
gblocks_time: "60:00:00"
trimal_time: "60:00:00"
iqtree_time: "60:00:00"
common_ids_time: "00:30:00"

#---- Tool paths ----
busco_path:
busco_dataset_path:
mafft_path:
gblocks_path:
trimal_path:
iqtree_path:

#---- Tool variables ----
busco_mode: "genome"
augustus_species: "human"
mafft_dna_params: ""
mafft_protein_params: "--anysymbol"
gblocks_dna_params: "-t=d -p=t"
gblocks_protein_params: "-t=p -p=t"
trimal_dna_params: "-automated1"
trimal_protein_params: "-automated1"
iqtree_protein_params: ""
iqtree_dna_params: ""
split_size: 50      # job grouping

#---- Results file names ----
concat_fna_filename: "concat.aln.fna"
concat_faa_filename: "concat.aln.faa"
iqtree_fna_prefix: "iqtree.concat.aln.fna"
iqtree_faa_prefix: "iqtree.concat.aln.faa"